/* Briefings — store Claude Design handovers as templates and instances.
 *
 * Layout on disk:
 *   briefings/seed/<id>/        committed templates that ship with the module
 *   briefings/data/items/<id>/  runtime instances (created via duplicate)
 *
 * Each briefing is a folder with `briefing.json` + a set of static files
 * (HTML/CSS/JS/assets) that render as a self-contained design. The backend
 * serves them at /api/briefings/view/<scope>/<id>/... so the frontend can
 * iframe them — and a future Cloudflare tunnel can re-export the same
 * URL shape publicly without changes.
 */

import { promises as fs, existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { spawn } from 'node:child_process';
import { tmpdir } from 'node:os';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

const SEED_DIR = path.join(__dirname, 'seed');

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.htm':  'text/html; charset=utf-8',
  '.css':  'text/css; charset=utf-8',
  '.js':   'application/javascript; charset=utf-8',
  '.jsx':  'application/javascript; charset=utf-8',
  '.mjs':  'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg':  'image/svg+xml',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.gif':  'image/gif',
  '.pdf':  'application/pdf',
  '.woff': 'font/woff',
  '.woff2':'font/woff2',
  '.ttf':  'font/ttf',
  '.txt':  'text/plain; charset=utf-8',
  '.md':   'text/plain; charset=utf-8',
};

const ID_RE = /^[a-z0-9][a-z0-9_-]*$/;

function rootFor(scope, itemsDir) {
  if (scope === 'seed') return SEED_DIR;
  if (scope === 'item') return itemsDir;
  return null;
}

async function readMeta(dir, fallbackId) {
  let raw;
  try { raw = await fs.readFile(path.join(dir, 'briefing.json'), 'utf8'); }
  catch { return null; }
  let meta;
  try { meta = JSON.parse(raw); } catch { return null; }
  return {
    name:        typeof meta.name        === 'string' ? meta.name        : fallbackId,
    description: typeof meta.description === 'string' ? meta.description : '',
    kind:        meta.kind === 'instance' ? 'instance' : 'template',
    entry:       typeof meta.entry       === 'string' ? meta.entry       : 'index.html',
    source:      typeof meta.source      === 'string' ? meta.source      : '',
    createdAt:   typeof meta.createdAt   === 'string' ? meta.createdAt   : null,
    publishUrl:  typeof meta.publishUrl  === 'string' ? meta.publishUrl  : null,
    publishedAt: typeof meta.publishedAt === 'string' ? meta.publishedAt : null,
    // Privacy state.
    lock:        meta.lock && typeof meta.lock === 'object' && typeof meta.lock.password === 'string'
                   ? { password: meta.lock.password } : null,
    expiresAt:   typeof meta.expiresAt   === 'string' ? meta.expiresAt   : null,
    unpublishedAt: typeof meta.unpublishedAt === 'string' ? meta.unpublishedAt : null,
    // Parent linkage. One level only — a child cannot itself be a parent.
    parentId:    typeof meta.parentId    === 'string' && ID_RE.test(meta.parentId)
                   ? meta.parentId : null,
  };
}

// Patch fields into a briefing's briefing.json without losing unknown keys.
async function patchMeta(briefingDir, fallbackId, patch) {
  let raw = '{}';
  try { raw = await fs.readFile(path.join(briefingDir, 'briefing.json'), 'utf8'); } catch {}
  let cur = {};
  try { cur = JSON.parse(raw); } catch {}
  const next = { ...cur, ...patch };
  await fs.writeFile(
    path.join(briefingDir, 'briefing.json'),
    JSON.stringify(next, null, 2) + '\n',
    'utf8',
  );
  return readMeta(briefingDir, fallbackId);
}

// Friendly password — three words + two digits, easy to type.
function generatePassword() {
  const A = ['blue','green','red','gold','warm','cool','quiet','quick','calm','sharp','bold','soft','copper','amber'];
  const B = ['stone','river','field','cloud','tree','peak','plain','star','bell','tide','bridge','wing','pine','ridge'];
  const pick = (xs) => xs[Math.floor(Math.random() * xs.length)];
  return pick(A) + '-' + pick(B) + '-' + Math.floor(10 + Math.random() * 90);
}

// Vercel Edge Middleware (auto-generated on each publish). Inlines the
// per-briefing lock + expiry settings so we don't need a runtime store
// on the deployed side. Lives at <publishRoot>/middleware.ts; Vercel
// picks it up automatically and runs it on every matching request.
function renderMiddlewareSource(config) {
  return `// Auto-generated by atelier briefings on each publish — do not edit by hand.
// Lives at the dist root so Vercel runs it as an Edge Function on every
// request. Per-briefing lock + expiry settings are inlined below; if a
// briefing has neither, it never reaches the gates here.

const CONFIG = ${JSON.stringify(config, null, 2)};

export const config = {
  // Skip Vercel's own asset paths so this never ships their requests
  // through the gate logic.
  matcher: '/((?!_next|_vercel|favicon).*)',
};

export default function middleware(req) {
  const url = new URL(req.url);
  const m = url.pathname.match(/^\\/([a-z0-9][a-z0-9_-]*)\\//);
  if (!m) return;
  const id = m[1];
  const c = CONFIG[id];
  if (!c) return;

  if (c.expiresAt && Date.now() > Date.parse(c.expiresAt)) {
    return new Response(
      '<!doctype html><html><head><meta charset="utf-8"><title>Expired</title></head>' +
      '<body style="font-family:ui-sans-serif,system-ui;text-align:center;padding:80px 24px;background:#fbf9f4;color:#2a3328">' +
      '<h1 style="font-weight:500;font-size:18px;margin:0 0 8px">This briefing has expired.</h1>' +
      '<p style="color:#6e6a5e;font-size:13px;margin:0">If you still need access, ask the sender to extend it.</p>' +
      '</body></html>',
      { status: 410, headers: { 'content-type': 'text/html; charset=utf-8' } }
    );
  }

  if (c.password) {
    const auth = req.headers.get('authorization') || '';
    const expected = 'Basic ' + btoa('briefing:' + c.password);
    if (auth !== expected) {
      return new Response('Authentication required', {
        status: 401,
        headers: { 'WWW-Authenticate': 'Basic realm="Briefing", charset="UTF-8"' },
      });
    }
  }
}
`;
}

async function regenerateMiddleware(publishRoot, ctx) {
  const itemsDir = path.join(ctx.dataDir, 'items');
  const config = {};
  for (const root of [SEED_DIR, itemsDir]) {
    let names = [];
    try { names = await fs.readdir(root); } catch { continue; }
    for (const name of names) {
      if (!ID_RE.test(name)) continue;
      const dir = path.join(root, name);
      let stat;
      try { stat = await fs.stat(dir); } catch { continue; }
      if (!stat.isDirectory()) continue;
      const meta = await readMeta(dir, name);
      if (!meta) continue;
      // Only gate briefings actually present in the dist (i.e., live).
      if (!existsSync(path.join(publishRoot, name))) continue;
      const c = {};
      if (meta.lock?.password) c.password = meta.lock.password;
      if (meta.expiresAt)      c.expiresAt = meta.expiresAt;
      if (Object.keys(c).length) config[name] = c;
    }
  }
  const mwPath = path.join(publishRoot, 'middleware.ts');
  if (!Object.keys(config).length) {
    await fs.rm(mwPath, { force: true });
    return;
  }
  await fs.writeFile(mwPath, renderMiddlewareSource(config), 'utf8');
}

// ── Feedback widget ─────────────────────────────────────────────────────
// Injected into every HTML page served by the briefing view route AND
// into pages materialized for the Vercel publish step. The widget is a
// self-contained vanilla DOM snippet: it never touches the briefing's
// own React/Babel runtime, just appends its own elements + script. The
// first thing it tries on submit is a same-origin POST to
//   /api/briefings/feedback/<scope>/<id>
// which works for the local-preview iframe but 404s on the public Vercel
// version. The fallback opens the user's mail client with the feedback
// pre-filled, so outside readers can still get notes back to you while
// we don't yet have a cloud-side ingest (Vercel KV) wired up.
function feedbackWidgetSnippet(scope, id) {
  return `
<style>
  .br-fab {
    position: fixed; bottom: 24px; right: 24px; z-index: 99999;
    width: 44px; height: 44px; border-radius: 22px;
    background: #2a3328; color: #fbf9f4; border: 0;
    display: flex; align-items: center; justify-content: center;
    cursor: pointer; box-shadow: 0 4px 14px rgba(0,0,0,0.18);
    font: 18px/1 ui-sans-serif, system-ui; padding: 0;
    transition: transform .15s ease, box-shadow .15s ease;
  }
  .br-fab:hover { transform: translateY(-1px); box-shadow: 0 6px 18px rgba(0,0,0,0.22); }
  .br-panel {
    position: fixed; bottom: 80px; right: 24px; z-index: 99999;
    width: 320px; max-width: calc(100vw - 48px);
    background: #fbf9f4; color: #2a3328;
    border: 1px solid #d8d2c4; border-radius: 6px;
    padding: 14px 16px; box-shadow: 0 12px 36px rgba(0,0,0,0.18);
    font: 13px/1.5 ui-sans-serif, system-ui;
    display: none;
  }
  .br-panel.open { display: block; }
  .br-panel-head { display:flex; justify-content:space-between; align-items:baseline; margin-bottom: 10px; }
  .br-panel-title { font-weight: 500; }
  .br-panel-close { background: transparent; border: 0; color: #8a8474; font-size: 18px; cursor: pointer; padding: 0; line-height: 1; }
  .br-anchor { background: #fdf6dd; border: 1px solid #efe5b8; padding: 6px 8px; border-radius: 3px; margin-bottom: 8px; font-size: 11px; color: #6b5d2e; max-height: 64px; overflow: auto; }
  .br-panel input, .br-panel textarea { width: 100%; box-sizing: border-box; border: 1px solid #d8d2c4; border-radius: 3px; padding: 6px 8px; font: inherit; margin-bottom: 8px; background: #fff; color: #2a3328; }
  .br-panel textarea { min-height: 80px; resize: vertical; }
  .br-panel button.br-send { background: #2a3328; color: #fbf9f4; border: 0; padding: 7px 14px; border-radius: 3px; cursor: pointer; font: inherit; }
  .br-panel button.br-send:disabled { opacity: .55; cursor: default; }
  .br-status { margin-top: 8px; font-size: 11px; color: #6e6a5e; }
  .br-status.error { color: #c54b3b; }
  .br-status a { color: inherit; text-decoration: underline; }
  /* Highlight + pin + popover for commented passages (Google-Docs-like). */
  ::highlight(br-comment) {
    background-color: rgba(252, 189, 47, 0.30);
    text-decoration: underline rgba(252, 189, 47, 0.85) wavy 2px;
  }
  .br-pin {
    position: absolute; z-index: 99997;
    width: 22px; height: 22px; border-radius: 11px;
    background: #fabd2f; color: #1d2021;
    font: 600 11px/22px ui-sans-serif, system-ui;
    text-align: center; cursor: pointer;
    box-shadow: 0 1px 4px rgba(0,0,0,0.18);
    border: 0; padding: 0;
    transition: transform .12s ease;
  }
  .br-pin:hover { transform: scale(1.12); }
  .br-pop {
    position: absolute; z-index: 99998;
    background: #fbf9f4; color: #2a3328;
    border: 1px solid #d8d2c4; border-radius: 6px;
    padding: 12px; max-width: 320px; min-width: 240px;
    box-shadow: 0 8px 28px rgba(0,0,0,0.18);
    font: 13px/1.5 ui-sans-serif, system-ui;
  }
  .br-pop-head { display:flex; justify-content:space-between; align-items:baseline; margin-bottom:8px; }
  .br-pop-title { font-weight:500; font-size: 12px; }
  .br-pop-x { background: transparent; border: 0; color: #8a8474; font-size: 16px; cursor: pointer; line-height: 1; padding: 0; }
  .br-pop-note { padding: 6px 0; border-bottom: 1px solid #ebe6d4; }
  .br-pop-note:last-child { border-bottom: 0; }
  .br-pop-from { color: #6b5d2e; font-size: 11px; margin-bottom: 4px; }
  .br-pop-msg { font-size: 13px; white-space: pre-wrap; }
  .br-pop-actions { display: flex; gap: 6px; margin-top: 6px; }
  .br-pop-resolve { background: #79740e; color: #fbf9f4; border: 0; padding: 4px 10px; border-radius: 3px; cursor: pointer; font: 11px ui-sans-serif, system-ui; }
  .br-pop-resolve:disabled { opacity: 0.5; cursor: default; }
</style>
<button class="br-fab" id="br-fab" title="Leave a note" aria-label="Leave a note">✎</button>
<div class="br-panel" id="br-panel" role="dialog" aria-label="Leave a note">
  <div class="br-panel-head">
    <div class="br-panel-title">Leave a note</div>
    <button class="br-panel-close" id="br-close" aria-label="Close">×</button>
  </div>
  <div class="br-anchor" id="br-anchor" style="display:none;"></div>
  <input id="br-from" placeholder="Your name (optional)" autocomplete="name" />
  <textarea id="br-msg" placeholder="What did you notice? Select text first to pin it."></textarea>
  <button class="br-send" id="br-send">Send</button>
  <div class="br-status" id="br-status"></div>
</div>
<script>
(function () {
  var SCOPE = ${JSON.stringify(scope)};
  var ID = ${JSON.stringify(id)};
  var $ = function (id) { return document.getElementById(id); };
  var fab = $('br-fab'), panel = $('br-panel'), anchorEl = $('br-anchor'),
      nameEl = $('br-from'), msgEl = $('br-msg'), sendBtn = $('br-send'),
      statusEl = $('br-status'), closeBtn = $('br-close');
  var anchor = '';
  // Triple-redundant selection capture. Browsers vary in when they
  // collapse the document selection on click, and some (Safari in
  // particular) ignore mousedown.preventDefault for focus changes. So we
  // catch the selection in three places, take whichever was most recent
  // when open() runs:
  //   • selectionchange — fires while the user drags
  //   • mousedown/touchstart on body — fires the instant the FAB or any
  //     other element is pressed, BEFORE the browser collapses anything
  //   • the live read inside open() itself
  var lastSelection = '';
  function snapshotSelection() {
    try {
      var s = String(window.getSelection() || '').replace(/\\s+/g, ' ').trim();
      if (s.length > 1) lastSelection = s;
    } catch (e) {}
  }
  document.addEventListener('selectionchange', snapshotSelection);
  // capture-phase mousedown so we run BEFORE any handler that might
  // collapse the selection (including the FAB's own preventDefault).
  document.addEventListener('mousedown', snapshotSelection, true);
  document.addEventListener('touchstart', snapshotSelection, true);

  function open() {
    panel.classList.add('open');
    var current = String(window.getSelection() || '').replace(/\\s+/g, ' ').trim();
    var sel = current.length > 1 ? current : lastSelection;
    if (sel && sel.length > 1) {
      anchor = sel.slice(0, 240);
      anchorEl.textContent = '“' + anchor + '”';
      anchorEl.style.display = 'block';
    } else {
      anchor = '';
      anchorEl.textContent = 'Tip: select text on the page first to pin this note to a passage.';
      anchorEl.style.display = 'block';
      anchorEl.style.fontStyle = 'normal';
      anchorEl.style.color = '#8a8474';
    }
    statusEl.textContent = ''; statusEl.classList.remove('error');
    setTimeout(function () { msgEl.focus(); }, 50);
  }
  function close() {
    panel.classList.remove('open');
    lastSelection = '';
    // restore default styling for the next open
    anchorEl.style.fontStyle = '';
    anchorEl.style.color = '';
  }
  // preventDefault on mousedown stops the focus shift that would otherwise
  // collapse the user's text selection before the click handler runs.
  fab.addEventListener('mousedown', function (e) { e.preventDefault(); });
  fab.addEventListener('click', function () { panel.classList.contains('open') ? close() : open(); });

  // ── Atelier scroll-to-anchor bridge ─────────────────────────────────
  // The atelier dashboard sends a postMessage when the user clicks a
  // note's pinned passage. We try the browser's window.find() first
  // (handles text spanning multiple nodes), fall back to a TreeWalker
  // scan, then briefly flash a yellow overlay over the matched range
  // so it stands out from the page.
  function flashRange(range) {
    // Use document coords (position: absolute relative to <body>) so the
    // overlay tracks the page even if the user scrolls afterwards. We
    // also wait one frame so any in-flight smooth-scroll has settled
    // before we measure — getClientRects() is viewport-relative and
    // changes during scroll animations.
    requestAnimationFrame(function () {
      var rects = range.getClientRects();
      var sx = window.pageXOffset || document.documentElement.scrollLeft || 0;
      var sy = window.pageYOffset || document.documentElement.scrollTop || 0;
      for (var i = 0; i < rects.length; i++) {
        var r = rects[i];
        var ov = document.createElement('div');
        ov.style.cssText = 'position:absolute;pointer-events:none;border-radius:3px;background:rgba(252,189,47,0.55);box-shadow:0 0 0 2px rgba(252,189,47,0.7);z-index:99998;transition:opacity 1.4s ease-out;';
        ov.style.left = (r.left + sx) + 'px';
        ov.style.top  = (r.top  + sy) + 'px';
        ov.style.width  = r.width  + 'px';
        ov.style.height = r.height + 'px';
        document.body.appendChild(ov);
        (function (el) {
          setTimeout(function () { el.style.opacity = '0'; }, 1500);
          setTimeout(function () { el.remove(); }, 3000);
        })(ov);
      }
    });
  }
  function findAndScroll(text) {
    if (!text) return false;
    var target = text.replace(/\\s+/g, ' ').trim().toLowerCase();
    if (!target) return false;
    // Walk every text node under <body>, skipping our own widget DOM.
    var walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, null);
    var node;
    while ((node = walker.nextNode())) {
      var parent = node.parentElement;
      if (parent && parent.closest && parent.closest('.br-panel, .br-fab')) continue;
      var raw = node.nodeValue || '';
      if (!raw.trim()) continue;
      // Match against the node's own normalized text. This handles
      // whitespace collapsing so the anchor "TO BE CONFIRMED" matches
      // even if the source has odd spacing — but stays per-node, so
      // anchors that span multiple <span>s won't be found. That's fine
      // for typical reader-pinned passages (which are short fragments
      // sitting inside one element) and avoids the complexity of
      // cross-node range reconstruction.
      var lower = raw.toLowerCase();
      var idx = lower.indexOf(target);
      if (idx < 0) {
        // Try with whitespace collapsed inside the node too.
        var collapsed = raw.replace(/\\s+/g, ' ');
        var collapsedLower = collapsed.toLowerCase();
        var ci = collapsedLower.indexOf(target);
        if (ci < 0) continue;
        // Map collapsed index back to raw index by walking.
        var rawIdx = 0, collIdx = 0, prevSpace = false;
        for (var j = 0; j < raw.length && collIdx < ci; j++) {
          var ch = raw[j];
          var isSpace = /\\s/.test(ch);
          if (isSpace) {
            if (!prevSpace) collIdx++;
            prevSpace = true;
          } else {
            collIdx++;
            prevSpace = false;
          }
          rawIdx = j + 1;
        }
        idx = rawIdx;
      }
      if (idx < 0 || idx + target.length > raw.length) continue;
      var range = document.createRange();
      range.setStart(node, idx);
      range.setEnd(node, Math.min(idx + target.length, raw.length));
      if (parent && parent.scrollIntoView) {
        // Instant scroll so flashRange reads the final viewport rects;
        // smooth animation would have us measure mid-scroll and place
        // the overlay where the text used to be, not where it is now.
        parent.scrollIntoView({ block: 'center' });
      }
      flashRange(range);
      return true;
    }
    console.warn('[briefings widget] anchor not found:', text);
    return false;
  }
  window.addEventListener('message', function (e) {
    var d = e && e.data;
    if (d && d.type === 'briefings.scrollTo' && typeof d.anchor === 'string') {
      // Defer slightly so the iframe has finished any tab-switch reflow
      // and the brochure's React mount has settled.
      setTimeout(function () { findAndScroll(d.anchor); }, 60);
    }
  });

  // ── Highlights & popover (Google-Docs-style commenting) ─────────────
  // When the atelier dashboard sends a list of open notes, decorate each
  // anchored passage with a yellow highlight + a clickable pin showing
  // the note count. Clicking the pin opens a popover with the notes and
  // a resolve button; resolving messages back to atelier so the local
  // feedback.json updates and the highlight disappears on the next
  // setHighlights round-trip.
  var br_groups = [];

  function brRelTime(iso) {
    if (!iso) return '';
    var t = new Date(iso).getTime();
    if (!Number.isFinite(t)) return '';
    var s = Math.floor((Date.now() - t) / 1000);
    if (s < 60) return 'just now';
    if (s < 3600) return Math.floor(s/60) + 'm ago';
    if (s < 86400) return Math.floor(s/3600) + 'h ago';
    return Math.floor(s/86400) + 'd ago';
  }

  function brFindRange(text) {
    if (!text) return null;
    var target = text.replace(/\\s+/g, ' ').trim().toLowerCase();
    if (!target) return null;
    var walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, null);
    var node;
    while ((node = walker.nextNode())) {
      var p = node.parentElement;
      if (p && p.closest && p.closest('.br-panel, .br-fab, .br-pin, .br-pop')) continue;
      var raw = node.nodeValue || '';
      if (!raw.trim()) continue;
      var idx = raw.toLowerCase().indexOf(target);
      if (idx < 0) continue;
      var range = document.createRange();
      range.setStart(node, idx);
      range.setEnd(node, Math.min(idx + target.length, raw.length));
      return range;
    }
    return null;
  }

  function clearHighlights() {
    var els = document.querySelectorAll('.br-pin, .br-pop');
    for (var i = 0; i < els.length; i++) els[i].remove();
    if (window.CSS && CSS.highlights) CSS.highlights.delete('br-comment');
    br_groups = [];
  }

  function placeBadge(group) {
    var rect = group.range.getBoundingClientRect();
    var sx = window.pageXOffset || document.documentElement.scrollLeft || 0;
    var sy = window.pageYOffset || document.documentElement.scrollTop || 0;
    var pin = document.createElement('button');
    pin.className = 'br-pin';
    pin.textContent = group.notes.length;
    pin.title = group.notes.length + ' note' + (group.notes.length === 1 ? '' : 's');
    pin.style.left = (rect.right + sx + 6) + 'px';
    pin.style.top  = (rect.top  + sy - 4) + 'px';
    pin.addEventListener('click', function (e) {
      e.stopPropagation();
      showPopover(group, pin);
    });
    document.body.appendChild(pin);
    group.pin = pin;
  }

  function showPopover(group, pin) {
    var existing = document.querySelectorAll('.br-pop');
    for (var i = 0; i < existing.length; i++) existing[i].remove();

    var pop = document.createElement('div');
    pop.className = 'br-pop';
    var pr = pin.getBoundingClientRect();
    var sx = window.pageXOffset || 0;
    var sy = window.pageYOffset || 0;
    var left = pr.right + sx + 8;
    var maxLeft = (sx + (window.innerWidth || document.documentElement.clientWidth)) - 340;
    if (left > maxLeft) left = Math.max(8, maxLeft);
    pop.style.left = left + 'px';
    pop.style.top  = (pr.top + sy) + 'px';

    var head = document.createElement('div');
    head.className = 'br-pop-head';
    var title = document.createElement('div');
    title.className = 'br-pop-title';
    title.textContent = group.notes.length + ' note' + (group.notes.length === 1 ? '' : 's');
    var x = document.createElement('button');
    x.className = 'br-pop-x';
    x.textContent = '×';
    x.addEventListener('click', function () { pop.remove(); });
    head.appendChild(title);
    head.appendChild(x);
    pop.appendChild(head);

    group.notes.forEach(function (n) {
      var div = document.createElement('div');
      div.className = 'br-pop-note';
      var meta = document.createElement('div');
      meta.className = 'br-pop-from';
      meta.textContent = (n.from || 'anonymous') + ' · ' + brRelTime(n.at);
      div.appendChild(meta);
      var msg = document.createElement('div');
      msg.className = 'br-pop-msg';
      msg.textContent = n.message;
      div.appendChild(msg);
      var actions = document.createElement('div');
      actions.className = 'br-pop-actions';
      var resolve = document.createElement('button');
      resolve.className = 'br-pop-resolve';
      resolve.textContent = 'resolve';
      resolve.addEventListener('click', function () {
        try { window.parent.postMessage({ type: 'briefings.resolve', id: n.id }, '*'); } catch (e) {}
        // Optimistic — atelier will send a fresh setHighlights soon and
        // this whole popover will disappear, but show feedback now too.
        div.style.opacity = '0.5';
        resolve.disabled = true;
        resolve.textContent = 'resolved';
      });
      actions.appendChild(resolve);
      div.appendChild(actions);
      pop.appendChild(div);
    });

    document.body.appendChild(pop);
  }

  function applyHighlights(notes) {
    clearHighlights();
    if (!Array.isArray(notes) || !notes.length) return;
    var byAnchor = {};
    for (var i = 0; i < notes.length; i++) {
      var n = notes[i];
      if (!n || !n.anchor || !n.id) continue;
      var k = String(n.anchor).replace(/\\s+/g, ' ').trim().toLowerCase();
      if (!k) continue;
      if (!byAnchor[k]) byAnchor[k] = { anchor: n.anchor, notes: [] };
      byAnchor[k].notes.push(n);
    }
    var ranges = [];
    Object.keys(byAnchor).forEach(function (k) {
      var g = byAnchor[k];
      var range = brFindRange(g.anchor);
      if (!range) return;
      g.range = range;
      ranges.push(range);
      placeBadge(g);
      br_groups.push(g);
    });
    if (window.CSS && CSS.highlights && window.Highlight && ranges.length) {
      try {
        var hl = new Highlight();
        ranges.forEach(function (r) { hl.add(r); });
        CSS.highlights.set('br-comment', hl);
      } catch (e) {}
    }
  }

  // Reposition badges on resize — viewports change, especially when the
  // user toggles atelier's sidebar. Throttled via rAF so a drag doesn't
  // flood the layout.
  var br_resizeRaf;
  window.addEventListener('resize', function () {
    if (br_resizeRaf) cancelAnimationFrame(br_resizeRaf);
    br_resizeRaf = requestAnimationFrame(function () {
      if (!br_groups.length) return;
      var notes = [];
      br_groups.forEach(function (g) { g.notes.forEach(function (n) { notes.push(n); }); });
      applyHighlights(notes);
    });
  });

  // Click outside the popover/pin closes it.
  document.addEventListener('click', function (e) {
    var t = e.target;
    if (t && t.closest && (t.closest('.br-pop') || t.closest('.br-pin'))) return;
    var pops = document.querySelectorAll('.br-pop');
    for (var i = 0; i < pops.length; i++) pops[i].remove();
  });

  // Extend the message listener with setHighlights handling. We attach a
  // second listener (the existing one stays focused on scrollTo) so the
  // two flows are independently maintainable.
  window.addEventListener('message', function (e) {
    var d = e && e.data;
    if (d && d.type === 'briefings.setHighlights') {
      // Defer briefly so a tab-switch / resize hasn't shifted the layout
      // out from under us when we measure rects.
      setTimeout(function () { applyHighlights(d.notes); }, 80);
    }
  });

  // ?scrollTo=<text> URL param: when present, jump to + flash that text
  // once the page has settled. Used by atelier and by the mailto fallback
  // so a recipient clicking the "open the page where I noted" link in
  // their email lands directly on the passage.
  try {
    var params = new URLSearchParams(window.location.search);
    var initialAnchor = params.get('scrollTo');
    if (initialAnchor) {
      // Wait long enough for runtime-Babel React to mount the brochure.
      var attempts = 0;
      var tick = function () {
        if (findAndScroll(initialAnchor)) return;
        if (++attempts < 12) setTimeout(tick, 500);
      };
      setTimeout(tick, 800);
    }
  } catch (e) {}
  closeBtn.addEventListener('click', close);
  document.addEventListener('keydown', function (e) { if (e.key === 'Escape') close(); });

  function mailtoFallback(msg) {
    var subject = encodeURIComponent('Note on briefing: ' + document.title);
    var body = encodeURIComponent(
      'On: ' + window.location.href + '\\n' +
      (anchor ? 'Re: “' + anchor + '”\\n' : '') +
      (nameEl.value.trim() ? 'From: ' + nameEl.value.trim() + '\\n' : '') +
      '\\n' + msg
    );
    return 'mailto:?subject=' + subject + '&body=' + body;
  }

  sendBtn.addEventListener('click', async function () {
    var msg = msgEl.value.trim();
    if (!msg) return;
    statusEl.classList.remove('error');
    statusEl.textContent = 'sending…';
    sendBtn.disabled = true;
    try {
      var r = await fetch('/api/briefings/feedback/' + SCOPE + '/' + ID, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          from: nameEl.value.trim() || 'anonymous',
          anchor: anchor || null,
          message: msg,
          pageUrl: window.location.href,
        }),
      });
      if (!r.ok) throw new Error('http ' + r.status);
      statusEl.textContent = 'sent · thanks';
      msgEl.value = '';
      setTimeout(close, 1400);
    } catch (err) {
      statusEl.classList.add('error');
      var href = mailtoFallback(msg);
      statusEl.innerHTML = "couldn't reach atelier — <a href='" + href + "'>email it instead</a>";
    } finally {
      sendBtn.disabled = false;
    }
  });
})();
</script>
`;
}

function injectFeedbackWidget(html, scope, id) {
  const widget = feedbackWidgetSnippet(scope, id);
  // Inject just before </body>; tolerate missing tag.
  if (/<\/body\s*>/i.test(html)) {
    return html.replace(/<\/body\s*>/i, widget + '\n</body>');
  }
  return html + widget;
}

// ── Sub-page support: breadcrumb + deep-dive resolver ────────────────────
// Both snippets are injected statically into served HTML. They use vanilla
// DOM (no React) so they sit alongside whatever the briefing's own runtime
// renders — same posture as the feedback widget. The deep-dive resolver
// runs once on load AND watches for new `[data-deepdive]` nodes via
// MutationObserver, so JSX-rendered buttons (like the Alberta seed's app.jsx)
// get their hrefs filled in once Babel mounts them.
//
// `base` is the URL prefix that resolves a child briefing's id to its root
// URL — `/api/briefings/view/item/` for atelier preview, `/` for the
// production Vercel deploy where every briefing sits at `/<id>/`.
function deepDiveResolverSnippet(base) {
  return `
<script>
(function () {
  var BASE = ${JSON.stringify(base)};
  function resolve(el) {
    var id = el.getAttribute('data-deepdive');
    if (!id) return;
    if (el.getAttribute('href')) return;
    el.setAttribute('href', BASE + id + '/');
  }
  function scan(root) {
    if (!root || !root.querySelectorAll) return;
    var els = root.querySelectorAll('[data-deepdive]');
    for (var i = 0; i < els.length; i++) resolve(els[i]);
  }
  scan(document);
  if (typeof MutationObserver !== 'undefined' && document.body) {
    new MutationObserver(function (records) {
      for (var i = 0; i < records.length; i++) {
        var added = records[i].addedNodes;
        for (var j = 0; j < added.length; j++) {
          var n = added[j];
          if (!n || n.nodeType !== 1) continue;
          if (n.matches && n.matches('[data-deepdive]')) resolve(n);
          scan(n);
        }
      }
    }).observe(document.body, { childList: true, subtree: true });
  }
})();
</script>
`;
}

// `parentHref` is where "back" goes (preview or production URL). The
// breadcrumb is a fixed-position bar at the top so it survives even if
// the briefing's own runtime mounts into <body> and reflows the page.
function breadcrumbSnippet(parentHref, parentName) {
  return `
<style>
  .br-crumb {
    position: fixed; top: 0; left: 0; right: 0; z-index: 99996;
    background: #2a3328; color: #fbf9f4;
    padding: 6px 14px; font: 12px/1.4 ui-monospace, "SF Mono", Menlo, Consolas, monospace;
    text-decoration: none; display: block;
    border-bottom: 1px solid #1d2021;
    box-shadow: 0 1px 4px rgba(0,0,0,0.18);
  }
  .br-crumb:hover { background: #3a4538; }
  body { margin-top: 30px; }
</style>
<a class="br-crumb" href="${escapeHtml(parentHref)}">← back to ${escapeHtml(parentName)}</a>
`;
}

function injectBreadcrumb(html, parentHref, parentName) {
  const snip = breadcrumbSnippet(parentHref, parentName);
  if (/<body[^>]*>/i.test(html)) {
    return html.replace(/<body[^>]*>/i, (m) => m + '\n' + snip);
  }
  return snip + html;
}

function injectDeepDiveResolver(html, base) {
  const snip = deepDiveResolverSnippet(base);
  if (/<\/body\s*>/i.test(html)) {
    return html.replace(/<\/body\s*>/i, snip + '\n</body>');
  }
  return html + snip;
}

// ── PDF attachments: previews + inline rendering ─────────────────────────
// Convention: drop PDFs into briefings/data/items/<id>/attachments/. In the
// briefing source, write `<a data-pdf="attachments/foo.pdf">caption</a>`.
// At render time (local view AND publish) the resolver below ENHANCES the
// anchor — keeps the same DOM node but gives it an href + injects a
// <img> preview + caption + "view full document" CTA inside. Same posture
// as the deep-dive resolver: works with both static HTML and JSX-mounted
// briefings (MutationObserver picks up React-rendered nodes), and React's
// reconciler is undisturbed because we don't replace nodes — we decorate
// the original anchor in place.
//
// Preview images are JPGs rendered by macOS `sips` from the PDF's first
// page, cached at `<dir>/attachments/.previews/<basename>.jpg` and
// regenerated only when the PDF's mtime exceeds the preview's. The
// publish step calls ensurePdfPreview for every attachments/*.pdf before
// copying into the dist; the local view route generates them lazily on
// first request.

async function ensurePdfPreview(briefingDir, pdfRelPath) {
  // pdfRelPath is something like "attachments/foo.pdf" — we honor whatever
  // dir the author put the file in, with .previews as a sibling within
  // the same dir. Returns the relative path of the preview, or null if
  // anything failed (caller decides whether to fall back gracefully).
  if (!/\.pdf$/i.test(pdfRelPath)) return null;
  const pdfAbs = safeJoin(briefingDir, pdfRelPath);
  if (!pdfAbs) return null;
  let pdfStat;
  try { pdfStat = await fs.stat(pdfAbs); }
  catch { return null; }
  if (!pdfStat.isFile()) return null;

  const dir = path.dirname(pdfRelPath);
  const base = path.basename(pdfRelPath).replace(/\.pdf$/i, '.jpg');
  const previewRel = path.join(dir, '.previews', base);
  const previewAbs = safeJoin(briefingDir, previewRel);
  if (!previewAbs) return null;

  // Cache hit: preview newer than (or equal to) the PDF.
  try {
    const prevStat = await fs.stat(previewAbs);
    if (prevStat.mtimeMs >= pdfStat.mtimeMs) return previewRel;
  } catch {}

  await fs.mkdir(path.dirname(previewAbs), { recursive: true });
  return new Promise((resolve) => {
    const proc = spawn('/usr/bin/sips', [
      '-s', 'format', 'jpeg',
      '-s', 'formatOptions', '85',
      '-Z', '1200',
      pdfAbs, '--out', previewAbs,
    ], { stdio: 'ignore' });
    const timer = setTimeout(() => proc.kill('SIGKILL'), 30000);
    proc.on('close', (code) => {
      clearTimeout(timer);
      resolve(code === 0 ? previewRel : null);
    });
    proc.on('error', () => { clearTimeout(timer); resolve(null); });
  });
}

// Pre-generate previews for every attachments/*.pdf in a briefing dir.
// Errors don't abort — a missing preview just falls back to a broken
// <img> on the page, which is bad but recoverable, while a hard fail
// would block the whole publish.
async function ensureAllPdfPreviews(briefingDir) {
  const att = path.join(briefingDir, 'attachments');
  let entries;
  try { entries = await fs.readdir(att, { withFileTypes: true }); }
  catch { return; }
  for (const ent of entries) {
    if (!ent.isFile() || !/\.pdf$/i.test(ent.name)) continue;
    await ensurePdfPreview(briefingDir, path.join('attachments', ent.name));
  }
}

// Inline CSS + runtime enhancer. Mirrors deepDiveResolverSnippet's shape:
// scan once + MutationObserver to catch JSX-mounted nodes. The enhancer
// decorates the anchor in place (sets href, populates innerHTML with
// preview img + caption + cta) instead of swapping the node, so React's
// reconciler doesn't fight us on subsequent re-renders.
function pdfAttachmentSnippet() {
  return `
<style>
  a.pdf-attachment, a[data-pdf-resolved] {
    display: block;
    margin: 24px 0;
    padding: 0;
    border: 1px solid #d8d2c4;
    border-radius: 4px;
    background: #fff;
    color: inherit;
    text-decoration: none;
    overflow: hidden;
    transition: box-shadow .18s ease, transform .18s ease;
  }
  a.pdf-attachment:hover, a[data-pdf-resolved]:hover {
    box-shadow: 0 6px 18px rgba(0,0,0,0.10);
    transform: translateY(-1px);
  }
  a.pdf-attachment .pdf-preview, a[data-pdf-resolved] .pdf-preview {
    display: block;
    width: 100%;
    height: auto;
    border-bottom: 1px solid #ebe6d4;
    background: #fbf9f4;
  }
  a.pdf-attachment .pdf-cta, a[data-pdf-resolved] .pdf-cta {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    gap: 12px;
    padding: 10px 14px;
    font: 12px/1.4 ui-monospace, "SF Mono", Menlo, Consolas, monospace;
    color: #2a3328;
  }
  a.pdf-attachment .pdf-cta-label, a[data-pdf-resolved] .pdf-cta-label {
    flex: 1; min-width: 0;
    overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
    font-weight: 500;
  }
  a.pdf-attachment .pdf-cta-action, a[data-pdf-resolved] .pdf-cta-action {
    flex: 0 0 auto;
    color: #6b5d2e;
  }
</style>
<script>
(function () {
  function previewFor(src) {
    var i = src.lastIndexOf('/');
    var dir = i >= 0 ? src.slice(0, i) : '';
    var base = src.slice(i + 1).replace(/\\.pdf$/i, '.jpg');
    return (dir ? dir + '/' : '') + '.previews/' + base;
  }
  function escAttr(s) {
    return String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;')
      .replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }
  function escText(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }
  function enhance(el) {
    if (!el || el.dataset.pdfResolved) return;
    var src = el.getAttribute('data-pdf');
    if (!src) return;
    var caption = (el.textContent || '').trim();
    el.setAttribute('href', src);
    el.setAttribute('target', '_blank');
    el.setAttribute('rel', 'noopener noreferrer');
    el.classList.add('pdf-attachment');
    el.dataset.pdfResolved = '1';
    var labelHtml = caption
      ? '<span class="pdf-cta-label">' + escText(caption) + '</span>'
      : '<span class="pdf-cta-label" style="color:#8a8474">PDF document</span>';
    el.innerHTML =
      '<img class="pdf-preview" src="' + escAttr(previewFor(src)) + '"' +
        ' alt="' + escAttr(caption || 'PDF preview') + '"' +
        ' loading="lazy" />' +
      '<span class="pdf-cta">' +
        labelHtml +
        '<span class="pdf-cta-action">view full document ↗</span>' +
      '</span>';
  }
  function scan(root) {
    if (!root || !root.querySelectorAll) return;
    var els = root.querySelectorAll('a[data-pdf]:not([data-pdf-resolved])');
    for (var i = 0; i < els.length; i++) enhance(els[i]);
  }
  scan(document);
  if (typeof MutationObserver !== 'undefined' && document.body) {
    new MutationObserver(function (records) {
      for (var i = 0; i < records.length; i++) {
        var added = records[i].addedNodes;
        for (var j = 0; j < added.length; j++) {
          var n = added[j];
          if (!n || n.nodeType !== 1) continue;
          if (n.matches && n.matches('a[data-pdf]:not([data-pdf-resolved])')) enhance(n);
          scan(n);
        }
      }
    }).observe(document.body, { childList: true, subtree: true });
  }
})();
</script>
`;
}

function injectPdfAttachments(html) {
  const snip = pdfAttachmentSnippet();
  if (/<\/body\s*>/i.test(html)) {
    return html.replace(/<\/body\s*>/i, snip + '\n</body>');
  }
  return html + snip;
}

// ── Feedback storage ────────────────────────────────────────────────────
function feedbackFile(briefingDir) {
  return path.join(briefingDir, 'feedback.json');
}
async function readFeedback(briefingDir) {
  try {
    const raw = await fs.readFile(feedbackFile(briefingDir), 'utf8');
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch { return []; }
}
async function writeFeedback(briefingDir, list) {
  await fs.writeFile(feedbackFile(briefingDir), JSON.stringify(list, null, 2) + '\n', 'utf8');
}

function escapeHtml(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// The dist folder for Vercel deploys. The first deploy was set up by hand
// (via the user's `vercel login` + a one-time `npx vercel --prod --yes`),
// which writes `.vercel/project.json` here binding this folder to the
// "briefings" project. Every subsequent publish reuses that link.
function publishRootFor(ctx) {
  return path.join(ctx.dataDir, 'publish', 'briefings');
}

// Single-flight: if a publish is in progress, reject concurrent ones rather
// than racing two `vercel deploy` invocations against the same folder.
let publishInflight = false;

async function listScope(rootDir) {
  let entries = [];
  try { entries = await fs.readdir(rootDir); } catch { return []; }
  const out = [];
  for (const name of entries) {
    if (!ID_RE.test(name)) continue;
    const dir = path.join(rootDir, name);
    let stat;
    try { stat = await fs.stat(dir); } catch { continue; }
    if (!stat.isDirectory()) continue;
    const meta = await readMeta(dir, name);
    if (!meta) continue;
    out.push({ id: name, dir, ...meta });
  }
  return out;
}

async function copyDir(src, dst) {
  await fs.mkdir(dst, { recursive: true });
  for (const ent of await fs.readdir(src, { withFileTypes: true })) {
    const s = path.join(src, ent.name);
    const d = path.join(dst, ent.name);
    if (ent.isDirectory()) await copyDir(s, d);
    else if (ent.isFile()) await fs.copyFile(s, d);
  }
}

function genId(name) {
  const slug = String(name || 'briefing')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40) || 'briefing';
  return `${slug}-${randomBytes(3).toString('hex')}`;
}

function safeJoin(rootDir, relPath) {
  // Prevent traversal: resolved target must stay under root.
  const target = path.resolve(rootDir, relPath || '.');
  const rootAbs = path.resolve(rootDir);
  if (target !== rootAbs && !target.startsWith(rootAbs + path.sep)) return null;
  return target;
}

// Locate a Chromium-family browser for headless PDF print. The launchd
// agent runs as the user, so the standard /Applications paths work. If
// none of these is present we surface a clear 503 from the PDF route.
const CHROME_CANDIDATES = [
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary',
  '/Applications/Chromium.app/Contents/MacOS/Chromium',
  '/Applications/Brave Browser.app/Contents/MacOS/Brave Browser',
  '/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge',
  '/Applications/Arc.app/Contents/MacOS/Arc',
];
function findChrome() {
  for (const p of CHROME_CANDIDATES) if (existsSync(p)) return p;
  return null;
}

// Strip characters that are unsafe for HTTP headers / typical filesystems
// while preserving readable unicode. Matches what most desktop browsers
// will accept in `filename="…"` without RFC 5987 encoding.
function safeFilename(name) {
  const cleaned = String(name || 'briefing')
    .replace(/[ -"\\/]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim() || 'briefing';
  return cleaned.slice(0, 120);
}

async function regenerateLanding(publishRoot) {
  const entries = await fs.readdir(publishRoot, { withFileTypes: true });
  const items = [];
  for (const ent of entries) {
    if (!ent.isDirectory() || !ID_RE.test(ent.name)) continue;
    const m = await readMeta(path.join(publishRoot, ent.name), ent.name);
    if (m) items.push({ id: ent.name, ...m });
  }
  items.sort((a, b) => a.name.localeCompare(b.name));

  const li = items.map((b) => `
    <li>
      <a href="/${escapeHtml(b.id)}/">
        <div class="name">${escapeHtml(b.name)}</div>
        ${b.description ? `<div class="desc">${escapeHtml(b.description)}</div>` : ''}
      </a>
    </li>`).join('');

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Briefings</title>
<style>
  :root { color-scheme: light; }
  body { font-family: ui-monospace, "SF Mono", Menlo, Consolas, monospace;
    background: #fbf9f4; color: #2a3328; max-width: 640px;
    margin: 80px auto; padding: 0 24px; line-height: 1.55; }
  h1 { font-weight: 500; font-size: 18px; margin: 0 0 6px; }
  p  { color: #6e6a5e; margin: 0 0 32px; font-size: 13px; }
  ul { list-style: none; padding: 0; margin: 0; }
  li { border-top: 1px solid #e6e2d6; padding: 14px 0; }
  li:last-child { border-bottom: 1px solid #e6e2d6; }
  a  { color: #2a3328; text-decoration: none; display: block; }
  a:hover { color: #6b5d2e; }
  .name { font-size: 14px; }
  .desc { color: #8a8474; font-size: 12px; margin-top: 4px; }
</style>
</head>
<body>
<h1>Briefings</h1>
<p>Direct links — share the deep URL with the recipient.</p>
<ul>${li || '<li><div class="desc">No briefings published yet.</div></li>'}</ul>
</body>
</html>
`;
  await fs.writeFile(path.join(publishRoot, 'index.html'), html, 'utf8');
}

function runVercelDeploy(cwd) {
  return new Promise((resolve, reject) => {
    const proc = spawn('npx', ['-y', 'vercel@latest', '--prod', '--yes'], {
      cwd,
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env, FORCE_COLOR: '0', CI: '1' },
    });
    let stdout = '';
    let stderr = '';
    proc.stdout.on('data', (d) => { stdout += d; });
    proc.stderr.on('data', (d) => { stderr += d; });
    const timer = setTimeout(() => proc.kill('SIGKILL'), 180000);
    proc.on('close', (code) => {
      clearTimeout(timer);
      const out = stdout + '\n' + stderr;
      const alias      = (out.match(/Aliased:\s+(https:\/\/\S+)/)    || [])[1] || null;
      const deployment = (out.match(/Production:\s+(https:\/\/\S+)/) || [])[1] || null;
      if (code !== 0 && !alias && !deployment) {
        return reject(new Error(`vercel exited ${code}: ${(stderr || stdout).slice(-500).trim()}`));
      }
      resolve({ alias, deployment, stdout, stderr });
    });
    proc.on('error', reject);
  });
}

async function serveFile(absPath, res) {
  let stat;
  try { stat = await fs.stat(absPath); }
  catch { res.statusCode = 404; res.end('Not found'); return; }
  if (!stat.isFile()) { res.statusCode = 404; res.end('Not found'); return; }
  const buf = await fs.readFile(absPath);
  const type = MIME[path.extname(absPath).toLowerCase()] || 'application/octet-stream';
  res.writeHead(200, {
    'Content-Type': type,
    'Content-Length': buf.length,
    'Cache-Control': 'no-cache',
  });
  res.end(buf);
}

export default {
  async mountRoutes(router, ctx) {
    const itemsDir = path.join(ctx.dataDir, 'items');
    await fs.mkdir(itemsDir, { recursive: true });

    router.get('/api/briefings/list', async (_req, res) => {
      const seeds = await listScope(SEED_DIR);
      const items = await listScope(itemsDir);
      const all = [
        ...seeds.map((b) => ({ scope: 'seed', ...b })),
        ...items.map((b) => ({ scope: 'item', ...b })),
      ];
      // Layer in feedback counts so the UI can badge unread notes per
      // briefing without making N extra round-trips on every refresh.
      const briefings = await Promise.all(all.map(async (b) => {
        const fb = await readFeedback(b.dir);
        const openFeedback = fb.filter((f) => f.status !== 'resolved').length;
        const totalFeedback = fb.length;
        const { dir, ...rest } = b;
        return { ...rest, openFeedback, totalFeedback };
      }));
      res.json({ briefings });
    });

    // ── Feedback ────────────────────────────────────────────────────
    // Comments live in <briefingDir>/feedback.json as an array of
    // { id, at, status, from, anchor, message, pageUrl } objects.
    // Reader-side widget POSTs new ones; the dashboard lists / resolves /
    // deletes / pulls-as-prompt for the apply-via-Claude flow.
    function resolveBriefing(scope, id) {
      if (!ID_RE.test(id || '') || (scope !== 'seed' && scope !== 'item')) return null;
      const root = rootFor(scope, itemsDir);
      const dir = root && path.join(root, id);
      return dir && existsSync(dir) ? dir : null;
    }

    router.get('/api/briefings/feedback/:scope/:id', async (req, res) => {
      const { scope, id } = req.params;
      const dir = resolveBriefing(scope, id);
      if (!dir) return res.json({ error: 'briefing not found' }, 404);
      res.json({ feedback: await readFeedback(dir) });
    });

    router.post('/api/briefings/feedback/:scope/:id', async (req, res) => {
      const { scope, id } = req.params;
      const dir = resolveBriefing(scope, id);
      if (!dir) return res.json({ error: 'briefing not found' }, 404);
      let body = {};
      try { body = await req.json(); } catch {}
      const message = String(body.message || '').trim().slice(0, 4000);
      if (!message) return res.json({ error: 'message required' }, 400);
      const item = {
        id: randomUUID(),
        at: new Date().toISOString(),
        status: 'open',
        from: String(body.from || 'anonymous').trim().slice(0, 80) || 'anonymous',
        anchor: typeof body.anchor === 'string' && body.anchor.trim()
                  ? body.anchor.trim().slice(0, 280)
                  : null,
        message,
        pageUrl: typeof body.pageUrl === 'string' ? body.pageUrl.slice(0, 1000) : null,
      };
      const list = await readFeedback(dir);
      list.push(item);
      await writeFeedback(dir, list);
      ctx.broadcast({ type: 'feedback-added', scope, id, item });
      res.json({ ok: true, item });
    });

    router.post('/api/briefings/feedback/:scope/:id/resolve', async (req, res) => {
      const { scope, id } = req.params;
      const dir = resolveBriefing(scope, id);
      if (!dir) return res.json({ error: 'briefing not found' }, 404);
      let body = {};
      try { body = await req.json(); } catch {}
      const ids = Array.isArray(body.ids) ? body.ids
                : body.id ? [body.id]
                : [];
      const status = body.status === 'open' ? 'open' : 'resolved';
      const list = await readFeedback(dir);
      let n = 0;
      const updated = list.map((f) => {
        if (ids.includes(f.id) || (ids.length === 0 && status === 'resolved' && f.status !== 'resolved')) {
          n++;
          return { ...f, status, resolvedAt: status === 'resolved' ? new Date().toISOString() : null };
        }
        return f;
      });
      await writeFeedback(dir, updated);
      ctx.broadcast({ type: 'feedback-changed', scope, id });
      res.json({ ok: true, updated: n });
    });

    router.delete('/api/briefings/feedback/:scope/:id/:itemId', async (req, res) => {
      const { scope, id, itemId } = req.params;
      const dir = resolveBriefing(scope, id);
      if (!dir) return res.json({ error: 'briefing not found' }, 404);
      const list = await readFeedback(dir);
      const next = list.filter((f) => f.id !== itemId);
      await writeFeedback(dir, next);
      ctx.broadcast({ type: 'feedback-changed', scope, id });
      res.json({ ok: true, removed: list.length - next.length });
    });

    // Pulls cloud-side notes (from the published Vercel function) into the
    // local feedback.json. The function on Vercel writes incoming reader
    // notes to a Vercel Blob; atelier authenticates with the same blob
    // token and dedups by id so a pull is idempotent.
    function getBlobToken() {
      const envPath = path.join(publishRootFor(ctx), '.env.local');
      try {
        const raw = readFileSync(envPath, 'utf8');
        for (const line of raw.split('\n')) {
          const m = line.match(/^BLOB_READ_WRITE_TOKEN=(?:"?)(.+?)(?:"?)$/);
          if (m) return m[1];
        }
      } catch {}
      return null;
    }

    router.post('/api/briefings/pull-cloud', async (req, res) => {
      let body = {}; try { body = await req.json(); } catch {}
      const { fromScope, fromId } = body;
      if (!ID_RE.test(fromId || '') || (fromScope !== 'seed' && fromScope !== 'item')) {
        return res.json({ error: 'bad scope or id' }, 400);
      }
      const root = rootFor(fromScope, itemsDir);
      const dir = path.join(root, fromId);
      if (!existsSync(dir)) return res.json({ error: 'briefing not found' }, 404);
      const meta = await readMeta(dir, fromId);
      if (!meta?.publishUrl) return res.json({ error: 'briefing has not been published yet' }, 400);

      const token = getBlobToken();
      if (!token) {
        return res.json({
          error: 'BLOB_READ_WRITE_TOKEN missing in briefings/data/publish/briefings/.env.local — run a fresh `vercel env pull`',
        }, 412);
      }

      let fnUrl;
      try {
        const u = new URL(meta.publishUrl);
        fnUrl = `${u.origin}/api/briefings/feedback/${fromScope}/${fromId}`;
      } catch {
        return res.json({ error: 'cannot derive function URL from publishUrl' }, 500);
      }

      let cloudList = [];
      try {
        const r = await fetch(fnUrl, {
          headers: { Authorization: 'Bearer ' + token },
        });
        if (!r.ok) return res.json({ error: `cloud GET ${r.status}` }, 502);
        const j = await r.json();
        cloudList = Array.isArray(j.feedback) ? j.feedback : [];
      } catch (e) {
        return res.json({ error: 'fetch failed: ' + e.message }, 502);
      }

      const localList = await readFeedback(dir);
      const have = new Set(localList.map((x) => x.id));
      const fresh = cloudList.filter((x) => x && x.id && !have.has(x.id));
      if (fresh.length === 0) {
        return res.json({ ok: true, added: 0, total: localList.length });
      }
      const merged = [...localList, ...fresh].sort((a, b) =>
        String(a.at || '').localeCompare(String(b.at || ''))
      );
      await writeFeedback(dir, merged);
      ctx.broadcast({ type: 'feedback-changed', scope: fromScope, id: fromId });
      ctx.broadcast({ type: 'briefings-changed' });
      res.json({ ok: true, added: fresh.length, total: merged.length });
    });

    // Builds a ready-to-use Claude prompt that bundles every open comment
    // with its anchor + author. Frontend displays this with a copy button
    // and the `cd <briefingDir> && claude` line so the user can paste it
    // into a terminal session and let Claude work the file in place.
    router.get('/api/briefings/feedback/:scope/:id/prompt', async (req, res) => {
      const { scope, id } = req.params;
      const dir = resolveBriefing(scope, id);
      if (!dir) return res.json({ error: 'briefing not found' }, 404);
      const meta = await readMeta(dir, id);
      const list = (await readFeedback(dir)).filter((f) => f.status !== 'resolved');
      if (list.length === 0) {
        return res.json({ error: 'no open feedback to apply' }, 400);
      }
      const lines = [];
      lines.push(`You're editing the briefing "${meta?.name || id}". Apply the reader feedback below to the relevant source files in this folder (typically data.js for content, app.jsx for layout/structure, styles.css for visuals). For each feedback item, decide whether it's a content change, a structural change, or a "fyi only" with no edit needed. Make minimal, surgical edits — don't rewrite sections. Show me a summary of what you changed at the end.`);
      lines.push('');
      lines.push(`There are ${list.length} open feedback item${list.length === 1 ? '' : 's'}:`);
      lines.push('');
      list.forEach((f, i) => {
        lines.push(`### ${i + 1}. ${f.from} · ${new Date(f.at).toISOString().slice(0, 16).replace('T', ' ')}`);
        if (f.anchor) lines.push(`Pinned to: "${f.anchor}"`);
        lines.push('');
        lines.push(f.message);
        lines.push('');
      });
      const cwdRel = scope === 'seed'
        ? `briefings/seed/${id}`
        : `briefings/data/items/${id}`;
      const prompt = lines.join('\n');
      res.json({
        prompt,
        cwdAbs: dir,
        cwdRel,
        cmd: `cd "${cwdRel}" && claude`,
        openCount: list.length,
      });
    });

    // Static file server for a briefing's bundle. The viewer URL is
    //   /api/briefings/view/<scope>/<id>/[<rel-path>]
    // The atelier shell's router doesn't support a glob param, so we
    // register depth-1..4 variants and reassemble the relative path.
    // That covers every realistic briefing layout (the Alberta seed is
    // flat); deeper trees can extend this later.
    function viewHandler(extractRel) {
      return async (req, res) => {
        const { scope, id } = req.params;
        if (!ID_RE.test(id || '') || (scope !== 'seed' && scope !== 'item')) {
          res.statusCode = 400; res.end('Bad request'); return;
        }
        const root = rootFor(scope, itemsDir);
        if (!root) { res.statusCode = 404; res.end('Not found'); return; }
        const dir = path.join(root, id);
        if (!existsSync(dir)) { res.statusCode = 404; res.end('Not found'); return; }
        const rel = extractRel(req.params);
        let target;
        if (!rel) {
          const meta = await readMeta(dir, id);
          if (!meta) { res.statusCode = 404; res.end('Not found'); return; }
          target = safeJoin(dir, meta.entry);
        } else {
          target = safeJoin(dir, rel);
        }
        if (!target) { res.statusCode = 400; res.end('Bad path'); return; }
        // For HTML, serve with the feedback widget injected so notes can
        // round-trip back to atelier via the iframe preview. Also inject
        // the deep-dive resolver, the pdf-attachment enhancer, and (when
        // this briefing is a child) a fixed breadcrumb at the top pointing
        // back to its parent.
        if (/\.html?$/i.test(target)) {
          let html;
          try { html = await fs.readFile(target, 'utf8'); }
          catch { res.statusCode = 404; res.end('Not found'); return; }
          let out = injectFeedbackWidget(html, scope, id);
          out = injectDeepDiveResolver(out, '/api/briefings/view/item/');
          out = injectPdfAttachments(out);
          const meta = await readMeta(dir, id);
          if (meta?.parentId) {
            const parentRoot = rootFor('item', itemsDir);
            const parentDir  = path.join(parentRoot, meta.parentId);
            const parentMeta = existsSync(parentDir)
              ? await readMeta(parentDir, meta.parentId) : null;
            if (parentMeta) {
              out = injectBreadcrumb(
                out,
                `/api/briefings/view/item/${meta.parentId}/`,
                parentMeta.name,
              );
            }
          }
          res.writeHead(200, {
            'Content-Type': 'text/html; charset=utf-8',
            'Content-Length': Buffer.byteLength(out, 'utf8'),
            'Cache-Control': 'no-cache',
          });
          res.end(out);
          return;
        }

        // Lazy preview generation: when a .previews/<name>.jpg under any
        // attachments dir is requested and isn't on disk yet (or is older
        // than its source PDF), render it via sips before serving. The
        // request URL maps directly to the eventual file path, so the
        // briefing source can hard-code preview URLs without needing a
        // separate API endpoint.
        const previewMatch = rel && rel.match(/^(.*\/)?\.previews\/(.+)\.jpe?g$/i);
        if (previewMatch) {
          const dirRel  = previewMatch[1] || '';
          const baseName = previewMatch[2];
          const pdfRel  = dirRel + baseName + '.pdf';
          await ensurePdfPreview(dir, pdfRel);
        }
        await serveFile(target, res);
      };
    }

    // Root URL serves the entry HTML. Both trailing-slash and bare forms
    // work, but the frontend always uses the trailing-slash form so the
    // browser resolves relative imports under the briefing's own dir.
    router.get('/api/briefings/view/:scope/:id',  viewHandler(() => ''));
    router.get('/api/briefings/view/:scope/:id/', viewHandler(() => ''));
    router.get('/api/briefings/view/:scope/:id/:p1',
      viewHandler((p) => p.p1));
    router.get('/api/briefings/view/:scope/:id/:p1/:p2',
      viewHandler((p) => `${p.p1}/${p.p2}`));
    router.get('/api/briefings/view/:scope/:id/:p1/:p2/:p3',
      viewHandler((p) => `${p.p1}/${p.p2}/${p.p3}`));
    router.get('/api/briefings/view/:scope/:id/:p1/:p2/:p3/:p4',
      viewHandler((p) => `${p.p1}/${p.p2}/${p.p3}/${p.p4}`));

    // Find every item-scope briefing whose parentId === id.
    async function listChildrenOf(parentId) {
      const items = await listScope(itemsDir);
      return items.filter((b) => b.parentId === parentId);
    }

    router.post('/api/briefings/duplicate', async (req, res) => {
      let body = {};
      try { body = await req.json(); } catch {}
      const { fromScope, fromId } = body;
      const name = (body.name || '').trim();
      if (fromScope !== 'seed' && fromScope !== 'item') {
        return res.json({ error: 'fromScope must be "seed" or "item"' }, 400);
      }
      if (!ID_RE.test(fromId || '')) {
        return res.json({ error: 'invalid fromId' }, 400);
      }
      const fromRoot = rootFor(fromScope, itemsDir);
      const fromDir = path.join(fromRoot, fromId);
      if (!existsSync(fromDir)) return res.json({ error: 'source not found' }, 404);
      const fromMeta = await readMeta(fromDir, fromId);
      if (!fromMeta) return res.json({ error: 'source missing briefing.json' }, 400);

      const newId = genId(name || fromMeta.name);
      const newDir = path.join(itemsDir, newId);
      if (existsSync(newDir)) return res.json({ error: 'id collision, retry' }, 409);

      await copyDir(fromDir, newDir);
      const newMeta = {
        name: name || `${fromMeta.name} (copy)`,
        description: fromMeta.description,
        kind: 'instance',
        entry: fromMeta.entry,
        source: `Cloned from ${fromScope}:${fromId} on ${new Date().toISOString().slice(0, 10)}`,
        createdAt: new Date().toISOString(),
        // If the source itself is a child, the duplicate stays under the
        // same parent (handy for "duplicate this section"). If the source
        // is a parent, its children are recursively duplicated below.
        parentId: fromMeta.parentId || null,
      };
      await fs.writeFile(
        path.join(newDir, 'briefing.json'),
        JSON.stringify(newMeta, null, 2) + '\n',
        'utf8',
      );

      // Recursively duplicate children when the source is a parent. Each
      // child gets a fresh id and is rewired to point at the new parent.
      // (Depth is capped at 1, so children-of-children don't exist.)
      if (!fromMeta.parentId) {
        const children = await listChildrenOf(fromId);
        for (const child of children) {
          const childNewId = genId(child.name);
          const childNewDir = path.join(itemsDir, childNewId);
          if (existsSync(childNewDir)) continue;
          await copyDir(child.dir, childNewDir);
          const childMeta = {
            name: child.name,
            description: child.description,
            kind: 'instance',
            entry: child.entry,
            source: `Cloned from item:${child.id} on ${new Date().toISOString().slice(0, 10)}`,
            createdAt: new Date().toISOString(),
            parentId: newId,
          };
          await fs.writeFile(
            path.join(childNewDir, 'briefing.json'),
            JSON.stringify(childMeta, null, 2) + '\n',
            'utf8',
          );
        }
      }

      ctx.broadcast({ type: 'briefings-changed' });
      res.json({ ok: true, id: newId, scope: 'item' });
    });

    // Create a fresh empty child under the given parent. Parents must be
    // item-scope (seeds stay read-only — duplicate first, then add children
    // to the duplicate). One-level cap: a child can't itself be a parent.
    // The new child gets a minimal index.html placeholder so the iframe
    // has something to render before the user edits the source.
    router.post('/api/briefings/add-child', async (req, res) => {
      let body = {}; try { body = await req.json(); } catch {}
      const { parentId } = body;
      const name = (body.name || '').trim();
      if (!ID_RE.test(parentId || '')) {
        return res.json({ error: 'invalid parentId' }, 400);
      }
      const parentDir = path.join(itemsDir, parentId);
      if (!existsSync(parentDir)) {
        return res.json({ error: 'parent not found (must be an instance — duplicate a template first)' }, 404);
      }
      const parentMeta = await readMeta(parentDir, parentId);
      if (!parentMeta) return res.json({ error: 'parent missing briefing.json' }, 400);
      if (parentMeta.parentId) {
        return res.json({ error: 'one-level only — this briefing is already a child' }, 400);
      }

      const finalName = name || 'New section';
      const newId = genId(finalName);
      const newDir = path.join(itemsDir, newId);
      if (existsSync(newDir)) return res.json({ error: 'id collision, retry' }, 409);

      await fs.mkdir(newDir, { recursive: true });
      const placeholder = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(finalName)}</title>
<style>
  body { font-family: ui-monospace, "SF Mono", Menlo, Consolas, monospace;
    background: #fbf9f4; color: #2a3328; max-width: 640px;
    margin: 80px auto; padding: 0 24px; line-height: 1.6; }
  h1 { font-weight: 500; font-size: 18px; margin: 0 0 8px; }
  p  { color: #6e6a5e; font-size: 13px; }
  code { background: #f1ecdf; padding: 1px 5px; border-radius: 2px; }
</style>
</head>
<body>
<h1>${escapeHtml(finalName)}</h1>
<p>Child of <em>${escapeHtml(parentMeta.name)}</em>. Edit <code>briefings/data/items/${escapeHtml(newId)}/index.html</code> to fill this in — or duplicate a template into here.</p>
</body>
</html>
`;
      await fs.writeFile(path.join(newDir, 'index.html'), placeholder, 'utf8');
      const newMeta = {
        name: finalName,
        description: '',
        kind: 'instance',
        entry: 'index.html',
        source: `Child of item:${parentId} created ${new Date().toISOString().slice(0, 10)}`,
        createdAt: new Date().toISOString(),
        parentId,
      };
      await fs.writeFile(
        path.join(newDir, 'briefing.json'),
        JSON.stringify(newMeta, null, 2) + '\n',
        'utf8',
      );
      ctx.broadcast({ type: 'briefings-changed' });
      res.json({ ok: true, id: newId, scope: 'item' });
    });

    // PDF download — spawns headless Chrome against the briefing's view
    // URL on this same server, lets it run for up to PDF_TIMEOUT_MS so the
    // React+Babel runtime mounts, then streams back the printed PDF. The
    // page itself dictates print sizing via its own @page CSS — we don't
    // pass paper size flags so the design's own layout wins.
    const PDF_TIMEOUT_MS = 30000;
    router.get('/api/briefings/pdf/:scope/:id', async (req, res) => {
      const { scope, id } = req.params;
      if (!ID_RE.test(id || '') || (scope !== 'seed' && scope !== 'item')) {
        return res.json({ error: 'bad request' }, 400);
      }
      const root = rootFor(scope, itemsDir);
      const dir = root && path.join(root, id);
      if (!dir || !existsSync(dir)) return res.json({ error: 'not found' }, 404);
      const meta = await readMeta(dir, id);
      if (!meta) return res.json({ error: 'briefing.json missing' }, 400);

      const chrome = findChrome();
      if (!chrome) {
        return res.json({
          error: 'No Chromium-family browser found in /Applications. Install Google Chrome (or Chromium / Brave / Edge) to enable PDF download.',
        }, 503);
      }

      const host = req.headers.host || 'localhost:1844';
      const url = `http://${host}/api/briefings/view/${scope}/${id}/`;
      const tmpFile = path.join(tmpdir(), `briefing-${randomBytes(8).toString('hex')}.pdf`);

      let killed = false;
      const proc = spawn(chrome, [
        '--headless=new',
        '--disable-gpu',
        '--no-pdf-header-footer',
        '--no-sandbox',
        '--virtual-time-budget=10000',
        `--print-to-pdf=${tmpFile}`,
        url,
      ], { stdio: 'ignore' });

      const timer = setTimeout(() => { killed = true; proc.kill('SIGKILL'); }, PDF_TIMEOUT_MS);
      const code = await new Promise((resolve) => {
        proc.on('error', () => resolve(-1));
        proc.on('close', (c) => resolve(c ?? -1));
      });
      clearTimeout(timer);

      try {
        if (killed) return res.json({ error: 'PDF print timed out' }, 504);
        if (code !== 0 && !existsSync(tmpFile)) {
          return res.json({ error: `chrome exited with code ${code}` }, 500);
        }
        const buf = await fs.readFile(tmpFile);
        const filename = safeFilename(meta.name) + '.pdf';
        res.writeHead(200, {
          'Content-Type': 'application/pdf',
          'Content-Length': buf.length,
          'Content-Disposition': `attachment; filename="${filename}"`,
          'Cache-Control': 'no-cache',
        });
        res.end(buf);
      } finally {
        fs.rm(tmpFile, { force: true }).catch(() => {});
      }
    });

    // Materialize one briefing into the dist folder. Copies the source
    // tree, renames `entry` → index.html so the public URL stays clean,
    // and runs all HTML files through the same widget+breadcrumb+deep-dive
    // pipeline used by the local view route — but with the production base
    // URL (`/`) so links resolve to other published siblings, not back to
    // atelier. Used by both single publish and cascade publish.
    async function materializeIntoDist(publishRoot, sourceDir, sourceId, sourceScope, sourceMeta, parentMeta) {
      // Render any new/stale PDF previews into the SOURCE attachments
      // dir before copying — that way the dist folder gets both the PDFs
      // and their .previews/<name>.jpg images via the same copyDir, and
      // future publishes reuse the cached previews automatically.
      await ensureAllPdfPreviews(sourceDir);

      const targetDir = path.join(publishRoot, sourceId);
      await fs.rm(targetDir, { recursive: true, force: true });
      await copyDir(sourceDir, targetDir);

      if (sourceMeta.entry && sourceMeta.entry !== 'index.html') {
        const from = path.join(targetDir, sourceMeta.entry);
        const to   = path.join(targetDir, 'index.html');
        if (existsSync(from)) await fs.rename(from, to);
      }

      for (const ent of await fs.readdir(targetDir, { withFileTypes: true })) {
        if (!ent.isFile() || !/\.html?$/i.test(ent.name)) continue;
        const p = path.join(targetDir, ent.name);
        const html = await fs.readFile(p, 'utf8');
        let out = injectFeedbackWidget(html, sourceScope, sourceId);
        out = injectDeepDiveResolver(out, '/');
        out = injectPdfAttachments(out);
        if (parentMeta) {
          out = injectBreadcrumb(out, `/${parentMeta.id}/`, parentMeta.name);
        }
        await fs.writeFile(p, out, 'utf8');
      }
    }

    // Publish — materialize the briefing (and its children, if any) into
    // the dist folder and run a single `vercel deploy --prod`. The first-
    // ever publish must already have been done by hand so the dist root
    // contains .vercel/project.json; see the module README.
    //
    // Cascade rule: publishing a parent also publishes every existing
    // child (so deep-dive buttons aren't dead links). Lock and expire stay
    // per-child — they're not propagated. Children are fully republished
    // each time the parent is, which is what you want most of the time.
    router.post('/api/briefings/publish', async (req, res) => {
      if (publishInflight) {
        return res.json({ error: 'a publish is already in progress' }, 429);
      }
      let body = {};
      try { body = await req.json(); } catch {}
      const { fromScope, fromId } = body;
      if (fromScope !== 'seed' && fromScope !== 'item') {
        return res.json({ error: 'fromScope must be "seed" or "item"' }, 400);
      }
      if (!ID_RE.test(fromId || '')) {
        return res.json({ error: 'invalid fromId' }, 400);
      }
      const root = rootFor(fromScope, itemsDir);
      const briefingDir = path.join(root, fromId);
      if (!existsSync(briefingDir)) return res.json({ error: 'briefing not found' }, 404);
      const meta = await readMeta(briefingDir, fromId);
      if (!meta) return res.json({ error: 'briefing.json missing' }, 400);

      const publishRoot = publishRootFor(ctx);
      if (!existsSync(path.join(publishRoot, '.vercel', 'project.json'))) {
        return res.json({
          error: 'Vercel project not linked. Run the one-time setup from briefings/README.md first.',
        }, 412);
      }

      publishInflight = true;
      ctx.broadcast({ type: 'publish-started', scope: fromScope, id: fromId });
      try {
        await fs.mkdir(publishRoot, { recursive: true });

        // Build the publish set: this briefing, plus its children (if it's
        // a parent). When publishing a child directly, we still want the
        // breadcrumb in its served HTML pointing back at its parent — even
        // if the parent itself isn't currently published — so the link
        // shape is stable across local preview and production.
        let parentForChildPublish = null;
        if (meta.parentId) {
          const pDir = path.join(itemsDir, meta.parentId);
          if (existsSync(pDir)) {
            const pMeta = await readMeta(pDir, meta.parentId);
            if (pMeta) parentForChildPublish = { id: meta.parentId, name: pMeta.name };
          }
        }
        const targets = [{
          dir: briefingDir, id: fromId, scope: fromScope, meta,
          parent: parentForChildPublish,
        }];
        if (!meta.parentId) {
          const children = await listChildrenOf(fromId);
          for (const c of children) {
            targets.push({
              dir: c.dir, id: c.id, scope: 'item', meta: c,
              parent: { id: fromId, name: meta.name },
            });
          }
        }

        for (const t of targets) {
          await materializeIntoDist(publishRoot, t.dir, t.id, t.scope, t.meta, t.parent);
        }

        await regenerateLanding(publishRoot);
        await regenerateMiddleware(publishRoot, ctx);
        const result = await runVercelDeploy(publishRoot);

        const base = result.alias || result.deployment;
        if (!base) {
          return res.json({
            error: 'could not parse deploy URL from vercel output',
            stdout: result.stdout, stderr: result.stderr,
          }, 500);
        }
        const baseTrim = base.replace(/\/$/, '');
        const stamp = new Date().toISOString();

        for (const t of targets) {
          const url = `${baseTrim}/${t.id}/`;
          await patchMeta(t.dir, t.id, {
            publishUrl: url,
            publishedAt: stamp,
            unpublishedAt: null,
          });
        }

        const publishUrl = `${baseTrim}/${fromId}/`;
        ctx.broadcast({ type: 'briefings-changed' });
        ctx.broadcast({
          type: 'publish-finished', scope: fromScope, id: fromId, url: publishUrl,
          publishedChildren: targets.length - 1,
        });
        res.json({ ok: true, url: publishUrl, publishedChildren: targets.length - 1 });
      } catch (err) {
        ctx.broadcast({ type: 'publish-failed', scope: fromScope, id: fromId, error: err.message });
        res.json({ error: err.message }, 500);
      } finally {
        publishInflight = false;
      }
    });

    // ── Privacy: unpublish / lock / expire ──────────────────────────
    // Each action edits briefing.json + the dist tree, then runs a single
    // re-deploy. They share publishInflight with the main publish path
    // so the user can't trigger overlapping deploys.
    async function privacyDeploy() {
      const publishRoot = publishRootFor(ctx);
      if (!existsSync(path.join(publishRoot, '.vercel', 'project.json'))) {
        throw new Error('Vercel project not linked. Run the bootstrap from briefings/README.md first.');
      }
      await regenerateLanding(publishRoot);
      await regenerateMiddleware(publishRoot, ctx);
      return runVercelDeploy(publishRoot);
    }

    router.post('/api/briefings/unpublish', async (req, res) => {
      if (publishInflight) return res.json({ error: 'a publish is already in progress' }, 429);
      let body = {}; try { body = await req.json(); } catch {}
      const { fromScope, fromId } = body;
      if (fromScope !== 'seed' && fromScope !== 'item') return res.json({ error: 'fromScope must be "seed" or "item"' }, 400);
      if (!ID_RE.test(fromId || '')) return res.json({ error: 'invalid fromId' }, 400);
      const root = rootFor(fromScope, itemsDir);
      const briefingDir = path.join(root, fromId);
      if (!existsSync(briefingDir)) return res.json({ error: 'briefing not found' }, 404);
      const meta = await readMeta(briefingDir, fromId);
      publishInflight = true;
      try {
        const publishRoot = publishRootFor(ctx);
        const stamp = new Date().toISOString();
        // Cascade: unpublishing a parent takes its children offline too.
        // (A deep-dive button on the parent that points at a child whose
        // dist folder was just removed would 404 on the parent's URL,
        // which is itself gone — but if you re-publish only the parent
        // later you'd have orphan dist children anyway, so easier to keep
        // the lifecycle paired.)
        const targets = [{ dir: briefingDir, id: fromId }];
        if (meta && !meta.parentId) {
          const children = await listChildrenOf(fromId);
          for (const c of children) targets.push({ dir: c.dir, id: c.id });
        }
        for (const t of targets) {
          await fs.rm(path.join(publishRoot, t.id), { recursive: true, force: true });
          await patchMeta(t.dir, t.id, {
            publishUrl: null,
            unpublishedAt: stamp,
          });
        }
        await privacyDeploy();
        ctx.broadcast({ type: 'briefings-changed' });
        res.json({ ok: true, unpublishedChildren: targets.length - 1 });
      } catch (err) {
        res.json({ error: err.message }, 500);
      } finally {
        publishInflight = false;
      }
    });

    router.post('/api/briefings/lock', async (req, res) => {
      if (publishInflight) return res.json({ error: 'a publish is already in progress' }, 429);
      let body = {}; try { body = await req.json(); } catch {}
      const { fromScope, fromId } = body;
      if (fromScope !== 'seed' && fromScope !== 'item') return res.json({ error: 'bad fromScope' }, 400);
      if (!ID_RE.test(fromId || '')) return res.json({ error: 'invalid fromId' }, 400);
      const root = rootFor(fromScope, itemsDir);
      const briefingDir = path.join(root, fromId);
      if (!existsSync(briefingDir)) return res.json({ error: 'briefing not found' }, 404);
      const password = (typeof body.password === 'string' && body.password.trim())
        ? body.password.trim().slice(0, 64)
        : generatePassword();
      publishInflight = true;
      try {
        await patchMeta(briefingDir, fromId, { lock: { password } });
        await privacyDeploy();
        ctx.broadcast({ type: 'briefings-changed' });
        res.json({ ok: true, password });
      } catch (err) {
        res.json({ error: err.message }, 500);
      } finally {
        publishInflight = false;
      }
    });

    router.post('/api/briefings/unlock', async (req, res) => {
      if (publishInflight) return res.json({ error: 'a publish is already in progress' }, 429);
      let body = {}; try { body = await req.json(); } catch {}
      const { fromScope, fromId } = body;
      if (fromScope !== 'seed' && fromScope !== 'item') return res.json({ error: 'bad fromScope' }, 400);
      if (!ID_RE.test(fromId || '')) return res.json({ error: 'invalid fromId' }, 400);
      const root = rootFor(fromScope, itemsDir);
      const briefingDir = path.join(root, fromId);
      if (!existsSync(briefingDir)) return res.json({ error: 'briefing not found' }, 404);
      publishInflight = true;
      try {
        await patchMeta(briefingDir, fromId, { lock: null });
        await privacyDeploy();
        ctx.broadcast({ type: 'briefings-changed' });
        res.json({ ok: true });
      } catch (err) {
        res.json({ error: err.message }, 500);
      } finally {
        publishInflight = false;
      }
    });

    router.post('/api/briefings/expire', async (req, res) => {
      if (publishInflight) return res.json({ error: 'a publish is already in progress' }, 429);
      let body = {}; try { body = await req.json(); } catch {}
      const { fromScope, fromId } = body;
      if (fromScope !== 'seed' && fromScope !== 'item') return res.json({ error: 'bad fromScope' }, 400);
      if (!ID_RE.test(fromId || '')) return res.json({ error: 'invalid fromId' }, 400);
      const root = rootFor(fromScope, itemsDir);
      const briefingDir = path.join(root, fromId);
      if (!existsSync(briefingDir)) return res.json({ error: 'briefing not found' }, 404);
      // Accept either ISO string or null/empty to clear.
      let expiresAt = null;
      if (typeof body.expiresAt === 'string' && body.expiresAt.trim()) {
        const t = Date.parse(body.expiresAt);
        if (!Number.isFinite(t)) return res.json({ error: 'invalid expiresAt' }, 400);
        expiresAt = new Date(t).toISOString();
      }
      publishInflight = true;
      try {
        await patchMeta(briefingDir, fromId, { expiresAt });
        await privacyDeploy();
        ctx.broadcast({ type: 'briefings-changed' });
        res.json({ ok: true, expiresAt });
      } catch (err) {
        res.json({ error: err.message }, 500);
      } finally {
        publishInflight = false;
      }
    });

    router.delete('/api/briefings/item/:id', async (req, res) => {
      const { id } = req.params;
      if (!ID_RE.test(id || '')) return res.json({ error: 'invalid id' }, 400);
      const dir = path.join(itemsDir, id);
      if (!existsSync(dir)) return res.json({ error: 'not found' }, 404);
      // Cascade: deleting a parent removes its children too. Frontend
      // confirms with the user before the call (count is shown there).
      const children = await listChildrenOf(id);
      for (const child of children) {
        await fs.rm(child.dir, { recursive: true, force: true });
      }
      await fs.rm(dir, { recursive: true, force: true });
      ctx.broadcast({ type: 'briefings-changed' });
      res.json({ ok: true, removedChildren: children.length });
    });
  },
};
